Hotel/Hotel/Controllers/RoomController.cs
using Hotel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hotel.RoomService;
using Hotel.Filters;

namespace Hotel.Controllers
{
    public class RoomController : Controller
    {
        private RoomClient roomClient = new RoomClient();

        [VerifyUserSession(operation: "canCreateBooking")]
        public ActionResult Index()
        {
            RoomModel room = new RoomModel();
            room.date_checkin = DateTime.Now;
            room.date_checkout = DateTime.Now;
            return View(room);
        }

        [VerifyUserSession(operation: "canCreateBooking")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(RoomModel room)
        {

            if (ModelState.IsValid)
            {
                room.RoomList = roomClient.getRooms(room.date_checkin, room.date_checkout);
                if (room.RoomList.Length==0)
                {
                    TempData["infoMessage"] = "No hay habitaciones disponibles";
            
                }

            }
            return View(room);
        }
    }
}

Hotel/Hotel/Views/Room/Index.cshtml
@using Hotel.RoomService
@using Hotel.Models
@model  Hotel.Models.RoomModel

@{
    ViewBag.Title = "Habitaciones";
}

@RenderPage("~/Views/Shared/_slide.cshtml")
<div class="container container-mb">

    @RenderPage("~/Views/Room/SearchForm.cshtml", Model)

    @{
        if (@TempData["errorMessage"] != null)
        {
            <br />
            <div class="alert alert-danger">
                @{
                    @TempData["errorMessage"]
                }
            </div>
        }
    }

    @{
        if (@TempData["infoMessage"] != null)
        {
            <br />
            <div class="alert alert-info">
                @{
                    @TempData["infoMessage"]
                }
            </div>
        }
    }

    @*@{
                if (Model.RoomList != null)
                {
                    <table class="table table-striped text-center">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Número de Habitación</th>
                                <th scope="col">Tipo de habitación</th>
                                <th scope="col">Costo diario</th>
                                <th scope="col">Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var room in Model.RoomList)
                            {
                                <tr>
                                    <th scope="row">@Html.DisplayFor(m => room.id)</th>
                                    <td>@Html.DisplayFor(m => room.num_room)</td>
                                    <td>@Html.DisplayFor(m => room.type_room)</td>
                                    <td>@Html.DisplayFor(m => room.cost_room)</td>
                                    <td>
                                        @Html.ActionLink(
        linkText: "Reservar",
        actionName: "Create",
        controllerName: "Booking",
        routeValues: new
        {
            num_room = room.num_room,
            type_room = room.type_room,
            date_checkin = Model.date_checkin,
            date_checkout = Model.date_checkout
        },
        htmlAttributes: new { @class = "btn btn-outline-info my-2 my-sm-0" })
                                    </td>
                                </tr>
                            }



                        </tbody>
                    </table>

                }
            }*@

    <section class="">
        @{
            if (Model.RoomList != null)
            {
                <div class="row m-0 row-list-habitaciones">

                    @foreach (var room in Model.RoomList)
                    {
                        <div class="col-12 col-md-6 col-lg-4">
                            <div class="row m-0">
                                <div class="col-12 col-md-12 col-lg-12 habitaciones-box shadow-box-habitaciones">
                                    <img class="img-fluid w-100 img-habitaciones-border" src="~/Content/img/img-room-min.jpg" alt="Maseca">
                                    <div class="habitaciones-box-text">
                                        <h5><strong>@Html.DisplayFor(m => room.id) / @Html.DisplayFor(m => room.num_room)</strong></h5>
                                        <p>Tipo de habitación: <strong>@Html.DisplayFor(m => room.type_room)</strong></p>
                                        <p>Costo diario: <strong>¢@Html.DisplayFor(m => room.cost_room)</strong></p>


                                        @Html.ActionLink(
                                            linkText: "Reservar",
                                            actionName: "Create",
                                            controllerName: "Booking",
                                            routeValues: new
                                            {
                                                num_room = room.num_room,
                                                type_room = room.type_room,
                                                date_checkin = Model.date_checkin,
                                                date_checkout = Model.date_checkout
                                            },
                                            htmlAttributes: new { @class = "btn btn-outline-info my-2 my-sm-0" })

                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>
            }
        }
    </section>

</div>

Hotel/Hotel/Views/Room/SearchForm.cshtml
@using Hotel.Models

@model Hotel.Models.RoomModel

<main class="d-flex align-items-center mt-100 mb-50">
    <div class="container">
        <div class="card login-card">
            <div class="row no-gutters">
                <div class="col-12">
                    <div class="card-body">
                        <h1 class="title-heading">Reservar habitación</h1>
                        <p class="p-text">Seleccione una fecha de entrada y salida para verificar las habitaciones disponibles.</p>
                        @using (Html.BeginForm("Index", "Room", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            <div class="row">

                                <div class="col-12 col-md-5 paddinginputs">
                                    <div class="input-group">
                                        <div class="input-group-prepend responsivediv">
                                            <span class="input-group-text responsivespan">Entrada</span>
                                        </div>
                                        @Html.TextBoxFor(x => x.date_checkin, "{0:yyyy-MM-dd}",
                                       new { @class = "form-control", @type = "date", autofocus = "autofocus" })
                                    </div>
                                    @Html.ValidationMessageFor(x => x.date_checkin, null, new { @class = "text-danger" })
                                </div>
                                <div class="col-12  col-md-5 paddinginputs">
                                    <div class="input-group">
                                        <div class="input-group-prepend responsivediv">
                                            <span class="input-group-text responsivespan">Salida</span>
                                        </div>
                                        @Html.TextBoxFor(x => x.date_checkout, "{0:yyyy-MM-dd}",
                                      new { @class = "form-control", @type = "date", autofocus = "autofocus" })
                                    </div>
                                    @Html.ValidationMessageFor(x => x.date_checkout, null, new { @class = "text-danger" })
                                </div>
                                <div class="col-12  col-md-2 paddinginputs">
                                    <button type="submit" class="btn btn-block login-btn">Buscar</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>